///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String cart = 'images/cart.png';
  static const String cartSelected = 'images/cart_selected.png';
  static const String category = 'images/category.png';
  static const String categorySelected = 'images/category_selected.png';
  static const String defIconLoadNodata = 'images/def_icon_load_nodata.png';
  static const String haitan = 'images/haitan.jpg';
  static const String home = 'images/home.png';
  static const String homeSelected = 'images/home_selected.png';
  static const String icon = 'images/icon.jpg';
  static const String icon1 = 'images/icon1.png';
  static const String icon2 = 'images/icon2.png';
  static const String icon3 = 'images/icon3.png';
  static const String iconGoodsEmptyPlaceholder = 'images/icon_goods_empty_placeholder.png';
  static const String iconSvg = 'images/icon_svg.svg';
  static const String lake = 'images/lake.png';
  static const String mine = 'images/mine.png';
  static const String mineSelected = 'images/mine_selected.png';
  static const String night = 'images/night.jpg';
  static const String timg = 'images/timg.jpg';
  static const String twice = 'images/twice.jpg';

}
